### ISSUE TITLE
Ignore functionality: ignore based on pageUrl + fix when error at e.g. payload.network[1]

### ISSUE THREAD

**Issue by borhub** [jamielesouef/angular-trackjs#2]
Thanks for the updates.

1) In ```validateError()``` we currently check against ```payload.network[0]```, but e.g. in my case the network array contains more entries and my particular error is at index 1. Can we fix this?

2) The ```logError``` variable in ```onError()``` actually means "ignore error". Can it be renamed? It's quite confusing.

3) Could we add a criterium to ignore based on the URL of the page where the error occurred (not just based on the API URL)?

I'd like to do something like this:
```javascript
            {
                statusCode: 401,
                statusText: 'Unauthorized',
                method: 'POST',
                url: 'https://api.seek.com.au/v1/authenticate/jobseeker',
                pageUrl: /.*\/login.*/
            },
```

And then ```validateError()``` would need to look similar to this (I just hacked it on to demonstrate):

```javascript
                    angular.forEach(errorCriteria, function (errorTest, prop) {
                        if (errorTest instanceof RegExp) {
                            matchedCriteria.push(errorTest.test(prop === 'pageUrl' ? payload.url : networkResponse[prop]));
                        } else {
                            matchedCriteria.push(prop === 'pageUrl' ? errorTest === payload.url : errorTest === networkResponse[prop]);
                        }
                    });
```

**Comment by jamielesouef** [comment]
Fixed in v0.1.0
